version: "3"

services:
  db_2:
    image: mysql:5.7
    restart: always
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
    ports:
     - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: 123456

  wordpress:
    depends_on:
      - db_2
    image: wordpress:latest
    restart: always
    ports:
     - "8000:80"
    environment:
      WORDPRESS_DB_HOST: db_2:3306
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_PASSWORD: 123456